### ISSUE TITLE
Color naming

### ISSUE THREAD

**Issue by AsherJingkongChen** [Basketball-Competition-Dashboard/web#4]
# Color naming

## _What_ are the motivations or contexts?

I am bad at naming colors. I need someone to organize colors.

## _What_ are the expected behaviors or solutions?

Very reusable color set, supported with auto-completion in VSCode.

## Note

Make changes via pull requests

**Comment by yuching29** [comment]
what do you mean about color naming?
do you mean the color code?

**Comment by AsherJingkongChen** [comment]
@michelle871207 

> what do you mean about color naming? do you mean the color code?

For example, the header has a yellow background, with color code being `#ffc368`.

I except a name for `#ffc368`, for example:

- **CSS**:
```css
:root {
    --color-header-primary: #ffc368;
}
```

- **Sass**:
```sass
$color_header_primary: #ffc368
```

Then I can apply it to the header:

- **From CSS**:
```sass
header
    background-color: var(--color-header-primary)
```

- **From Sass**:
```sass
header
    background-color: $color_header_primary
```

Create a pull request or issue if you have an idea.

**Comment by AsherJingkongChen** [comment]
## Notice

I will use hardcoded color code everywhere because it is simple.
